[theme]
base = "dark"
primaryColor = "#818cf8"
backgroundColor = "#0a1120"
secondaryBackgroundColor = "#0f192e"
textColor = "#e2e8f0"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
